---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
...
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
...
